
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EKA
 */
public class FormInputTransaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormInputTransaksi.class.getName());

    /**
     * Creates new form FormInputTransaksi
     */
    public FormInputTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rowOutput = new javax.swing.JTable();
        lblidTransaksi = new javax.swing.JLabel();
        lblAkun = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        txtidTransaksi = new javax.swing.JTextField();
        txtidAkun = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        lbljenis = new javax.swing.JLabel();
        lbljumlah = new javax.swing.JLabel();
        lblketerangan = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtketerangan = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rowOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idTransaksi", "idAkun", "tanggal", "jenis", "jumlah", "keterangan"
            }
        ));
        rowOutput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rowOutputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rowOutput);

        lblidTransaksi.setText("idTransaksi");

        lblAkun.setText("idAkun");

        lbltanggal.setText("tanggal");

        lbljenis.setText("jenis");

        lbljumlah.setText("jumlah");

        lblketerangan.setText("keterangan");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lblAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(97, 97, 97)
                                .addComponent(btnClear)
                                .addGap(131, 131, 131)
                                .addComponent(btnEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtidAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbljumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbljenis, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtjumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txtketerangan)
                                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblidTransaksi)
                            .addComponent(txtidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbljenis)
                            .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAkun)
                    .addComponent(txtidAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljumlah)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltanggal)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblketerangan)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JTable tblData;
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String idTransaksi = txtidTransaksi.getText();
        String idAkun = txtidAkun.getText();
        String tanggal = txttanggal.getText();
        String jenis = txtjenis.getText();
        String jumlah = txtjumlah.getText();
        String keterangan = txtketerangan.getText();

    if (idTransaksi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Transaksi belum diisi");
        txtidTransaksi.requestFocus();
        return;
    }

    // Pastikan nama JTable sesuai dengan yang ada di Navigator
    DefaultTableModel model = (DefaultTableModel) tblData.getModel();
    model.addRow(new Object[]{idTransaksi, idAkun, tanggal, jenis, jumlah, keterangan});  
    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtidTransaksi.setText("");
        txtidAkun.setText("");
        txttanggal.setText("");
        txtjenis.setText("");
        txtjumlah.setText("");
        txtketerangan.setText("");
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
               
        int row = tblData.getSelectedRow();
        if (row == -1) {
              JOptionPane.showMessageDialog(this, 
              "Pilih baris yang ingin dihapus!", "Error",
              JOptionPane.WARNING_MESSAGE);
              return;
        }
        model.removeRow(row);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
    }//GEN-LAST:event_btnClearActionPerformed

    private void rowOutputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rowOutputMouseClicked
        int row = tblData.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        
        txtidTransaksi.setText(model.getValueAt(row, 0).toString());
        txtidAkun.setText(model.getValueAt(row, 1).toString());
        txttanggal.setText(model.getValueAt(row, 2).toString());
        txtjenis.setText(model.getValueAt(row, 3).toString());
        txtjumlah.setText(model.getValueAt(row, 4).toString());
        txtketerangan.setText(model.getValueAt(row, 5).toString());
        
    }//GEN-LAST:event_rowOutputMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
            int row = tblData.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Pilih yang ingin diedit", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            model.setValueAt(txtidTransaksi.getText(), row, 0);
            model.setValueAt(txtidAkun.getText(), row, 1);
            model.setValueAt(txttanggal.getText(), row, 2);
            model.setValueAt(txtjenis.getText(), row, 3);
            model.setValueAt(txtjumlah.getText(), row, 4);
            model.setValueAt(txtketerangan.getText(), row, 5);
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
    }//GEN-LAST:event_btnEditActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormInputTransaksi().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAkun;
    private javax.swing.JLabel lblidTransaksi;
    private javax.swing.JLabel lbljenis;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblketerangan;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JTable rowOutput;
    private javax.swing.JTextField txtidAkun;
    private javax.swing.JTextField txtidTransaksi;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
